// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQF6puuIBwx5t-y5_cv0qsM8oqtX9lalE',
    appId: '1:182544638557:web:be07d14caed94c43b3a3b4',
    messagingSenderId: '182544638557',
    projectId: 'smartfinance-c356b',
    authDomain: 'smartfinance-c356b.firebaseapp.com',
    storageBucket: 'smartfinance-c356b.firebasestorage.app',
    measurementId: 'G-LD812N4VY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_0cFCfONbs5nQi7gKK92aD-kQXl-q0w',
    appId: '1:182544638557:android:9df50f63d4df4ee3b3a3b4',
    messagingSenderId: '182544638557',
    projectId: 'smartfinance-c356b',
    storageBucket: 'smartfinance-c356b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyrPtss6CrUloKXUitEur_wUysY1DfLsg',
    appId: '1:182544638557:ios:766627d575a51b7eb3a3b4',
    messagingSenderId: '182544638557',
    projectId: 'smartfinance-c356b',
    storageBucket: 'smartfinance-c356b.firebasestorage.app',
    iosBundleId: 'com.example.smartFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyrPtss6CrUloKXUitEur_wUysY1DfLsg',
    appId: '1:182544638557:ios:766627d575a51b7eb3a3b4',
    messagingSenderId: '182544638557',
    projectId: 'smartfinance-c356b',
    storageBucket: 'smartfinance-c356b.firebasestorage.app',
    iosBundleId: 'com.example.smartFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQF6puuIBwx5t-y5_cv0qsM8oqtX9lalE',
    appId: '1:182544638557:web:aab4e6671a158eebb3a3b4',
    messagingSenderId: '182544638557',
    projectId: 'smartfinance-c356b',
    authDomain: 'smartfinance-c356b.firebaseapp.com',
    storageBucket: 'smartfinance-c356b.firebasestorage.app',
    measurementId: 'G-TJ4PTL7NNK',
  );
}
